FROM  golang:1.11.5

COPY . /go/src/github.com/gforghetti/docker-log-driver
RUN cd /go/src/github.com/gforghetti/docker-log-driver && go get && go build --ldflags '-extldflags "-static"' -o /usr/bin/docker-log-driver
